---
title: "Shiny Presentation"
author: "Badal Chowdhury"
date: "July 10, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Slide 1
Instructions

This peer assessed assignment has two parts. First, you will create a Shiny application and deploy it on Rstudio's servers. Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

Your Shiny Application

1.     Write a shiny application with associated supporting documentation.
       The documentation should be thought of as whatever a user will need         to get started suing your application
2.     Deploy the application on Rstudio's shiny server

## Slide 2
Steps followed for the App
1.  Created Account in Shinyapps.io
2.  Run the setAccountInfo
3.  library(rsconnect)
4.  library(shiny)
5.  deployApp("C:/Badal/RStudio/Shiny/MyApp")

It generated the Application file
https://badalc.shinyapps.io/myapp/

## Slide 3
server.R
library(shiny)

shinyServer(function(input, output) {
   
  output$distPlot <- renderPlot({
    
    set.seed(2016-10-25)
    no_points <- input$numeric
    minX <- input$sliderX[1]
   minY <- input$sliderY[1]
    maxX <- input$sliderX[2]
    maxY <- input$sliderY[2]
   datax <- runif(no_points, minX, maxX)
    datay <- runif(no_points, minY, maxY)
    xlab <- ifelse(input$show_xlab,"X-Axis","")
    ylab <- ifelse(input$show_ylab,"Y-Axis","")
    main <- ifelse(input$show_title,"Title","")
    
    plot(datax,datay,xlab = xlab, ylab = ylab, main = main,
         xlim = c(-100,100), ylim = c(-100,100))
    
  })
  
})

## Slide 4
ui.R

library(shiny)

# Define UI for application that draws a histogram
shinyUI(fluidPage(
  
  # Application title
  titlePanel("Old Random Number"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
      numericInput("numeric","How many random number should be plotted?",value=1000,min = 1,max = 1000, step = 1
                   ),
       sliderInput("sliderX",
                   "Pick minimum and maximum X values",
                   min = -100,
                   max = 100,
                   value = c(-50,50)
    ),
    sliderInput("sliderY",
                "Pick minimum and maximum Y values",
                min = -100,
                max = 100,
                value = c(-50,50)
    ),
    checkboxInput("show_xlab","Show/Hide X label", value = TRUE),
    checkboxInput("show_ylab","Show/Hide Y label", value = TRUE),
    checkboxInput("show_title","Show/Hide Title")
    ),
    # Show a plot of the generated distribution
    
    mainPanel(
       plotOutput("distPlot")
    )
  )
))

##Slide 5

github location:
https://github.com/badal2017/DevelopDataProducts

Shiny App link: https://badalc.shinyapps.io/myapp/

